import { Inter } from "next/font/google";
import HeaderMain from "./components/HeaderMain";
import HeaderTop from "./components/HeaderTop";
import NavBar from "./components/NavBar";
import "./globals.css";

import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderTop/>
      <HeaderMain/>
      <NavBar/>
      {children}</body>
    </html>
  );
}
