import { Inter } from "next/font/google";
import HeaderMain from "./components/HeaderMain";
import HeaderTop from "./components/HeaderTop";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderTop/>
      <HeaderMain/>
      {children}</body>
    </html>
  );
}
